site_name: "Loan Ranger"
docs_dir: docs
site_dir: ../site

repo_url: "https://github.com/NirnaethArniedi/loan_ranger"
repo_name: "loan_ranger"
edit_uri: "edit/main/"

theme:
  name: "material"
  palette:
    scheme: "slate"
    primary: "teal"
    accent: "cyan"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - codehilite
  - extra

nav:
  - Home: README.md

plugins:
  - search
  - mkdocs-autoapi:
      autoapi_dir: loan_ranger
      autoapi_ignore:
        - __main__.py
      autoapi_add_nav_entry: Reference
      autoapi_keep_files: True
      autoapi_root: api
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: loan-ranger

          options:
            backlinks: tree
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            docstring_style: numpy
            filters: public
            heading_level: 1
            inherited_members: true
            line_length: 88
            merge_init_into_class: true
            parameter_headings: true
            preload_modules: [mkdocstrings]
            relative_crossrefs: true
            scoped_crossrefs: true
            separate_signature: true
            show_bases: false
            show_inheritance_diagram: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true
